apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - name: pipeline
        image: royjith/pikube:latest-v1
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501 
  selector:
    app: pipeline
